routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/author', function() {
    return view('author.index');
})->name('author');

Auth::routes(['register' => false, 'reset' => false, 'confirm' => false]);

Route::group(['namespace' => 'Admin',  'prefix' => 'admin', 'middleware' => ['auth', 'role:super-admin|admin']], function () {
    Route::name('admin.')->group(function () {
        // MASTER
        Route::resource('/kelas', 'KelasController', ['except' => ['show']])->middleware('permission:see-kelas|add-kelas|edit-kelas|delete-kelas');
        Route::resource('/siswa', 'SiswaController', ['except' => ['show']])->middleware('permission:see-siswa|add-siswa|edit-siswa|delete-siswa');
        
        // Guru
        Route::resource('/guru', 'UserController', ['except' => ['show']])->middleware('permission:see-guru|add-guru|edit-guru|delete-guru');
        Route::resource('/mapel', 'MapelController', ['except' => ['show']])->middleware('permission:see-mapel|add-mapel|edit-mapel|delete-mapel');
        Route::resource('/pengajar', 'PengajarController', ['except' => ['show']])->middleware('permission:see-pengajar|add-pengajar|edit-pengajar|delete-pengajar');
        Route::resource('/jurusan', 'JurusanController', ['except' => ['show']])->middleware('permission:see-jurusan|add-jurusan|edit-jurusan|delete-jurusan');
        Route::resource('/wali-kelas', 'WaliKelasController', ['except' => ['show', 'edit', 'update']]);
        Route::resource('/tahun-ajar', 'TahunAjarController', ['except' => ['show']])->middleware('permission:see-tahun-ajar|add-tahun-ajar|edit-tahun-ajar|delete-tahun-ajar');
        // Settings Route
        Route::group(['middleware' => ['role:super-admin|admin', 'permission:edit-settings']], function () {
            Route::get('/settings', 'SettingController@index')->name('settings.index');
            Route::put('/settings', 'SettingController@update')->name('settings.update');
        });
    });
});

Route::group(['middleware' => ['auth', 'role:super-admin|admin|user']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    // Jurnal
    Route::resource('/jurnal', 'JurnalController');
    Route::resource('/wali-kelas', 'WaliKelasController');
    Route::get('/all-jurnal', 'JurnalController@all')->name('jurnal.all');
    Route::get('/jurnal/detail/{id}', 'JurnalController@show_detail')->name('jurnal.detail');
    Route::post('/jurnal/siswa', 'JurnalController@siswa')->name('jurnal.siswa');
    Route::post('/jurnal/mapel', 'JurnalController@mapel')->name('jurnal.mapel');
    Route::get('/laporan/print-sdm', 'LaporanController@print')->name('coba-print');
    // Route::get('/laporan/all-coba-print', 'LaporanController@allprintsdm')->name('all-coba-print');
    Route::get('/laporan/sdm', 'LaporanController@indexsdm')->name('laporan_sdm.index')->middleware('permission:see-laporan-sdm');
    // Route::get('/laporan/all-sdm', 'LaporanController@indexallsdm')->name('laporan_sdm.all')->middleware('permission:see-laporan-sdm');
    Route::get('/laporan/bk', 'LaporanController@indexbk')->name('laporan_bk.index')->middleware('permission:see-laporan-bk');
    
    // Edit Profile
    Route::get('/profile', 'UserController@index')->name('user.index');
    Route::put('/profile', 'UserController@updateProfile')->name('user.updateProfile');

    // Edit Password
    Route::get('/edit-password', 'UserController@password')->name('user.password');
    Route::put('/edit-password', 'UserController@updatePassword')->name('user.updatePassword');
});

app/Models/Pengajar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Kelas;
use App\Models\Mapel;
use App\Models\TahunAjar;
use App\User;

class Pengajar extends Model
{
    public $timestamps = false;
    protected $table = 'pengajar';

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function mapel() {
        return $this->belongsTo(Mapel::class);
    }

    public function kelas() {
        return $this->belongsTo(Kelas::class);
    }
    
    public function tahun_ajar() {
        return $this->belongsTo(TahunAjar::class);
    }
}

app/Http/Controllers/Admin/PengajarController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Pengajar\PengajarCreateRequest, App\Http\Requests\Pengajar\PengajarUpdateRequest;
use App\Models\Mapel;
use App\Models\Kelas;
use App\Models\Pengajar;
use App\Models\TahunAjar;
use App\User;
use DataTables;
use Alert;

class PengajarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $pengajar = Pengajar::with('user', 'mapel', 'kelas', 'tahun_ajar')->get();
            return DataTables::of($pengajar)
                            ->addColumn('action', function($pengajar) {
                                $button = "<a href=".route('admin.pengajar.edit', $pengajar->id)." class='btn btn-success'><i class='far fa-edit'></i></a>";
                                $button .= "&nbsp;&nbsp;";
                                $button .= "<button class='btn btn-danger' data-remote='".route('admin.pengajar.destroy', $pengajar->id)."'><i class='fas fa-trash-alt'></i></button>";
                                return $button;
                            })
                            ->rawColumns(['materi','tanggal','action'])
                            ->make(true);
        }
        
        return view('pages.admin.pengajar.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $mapel = Mapel::get();
        $kelas = Kelas::get();
        $guru = User::get();
        $tahunajar = TahunAjar::get();
        
        return view('pages.admin.pengajar.create', compact('kelas', 'guru', 'mapel', 'tahunajar'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PengajarCreateRequest $request)
    {
        $pengajar = new Pengajar;
        $pengajar->user_id = $request->user_id;
        $pengajar->mapel_id = $request->mapel_id;
        $pengajar->kelas_id = $request->kelas_id;
        $pengajar->tahun_ajar_id = $request->tahun_ajar_id;
        $pengajar->save();

        Alert::success('Sukses!', 'Data berhasil ditambahkan');
        return redirect(route('admin.pengajar.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pengajar = Pengajar::findOrFail($id);
        $mapel = Mapel::get();
        $kelas = Kelas::get();
        $guru = User::get();
        $tahunajar = TahunAjar::get();

        return view('pages.admin.pengajar.edit', compact('pengajar', 'mapel', 'kelas', 'guru', 'tahunajar'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PengajarUpdateRequest $request, $id)
    {
        $pengajar = Pengajar::findOrFail($id);
        $pengajar->mapel_id = $request->mapel_id;
        $pengajar->kelas_id = $request->kelas_id;
        $pengajar->tahun_ajar_id = $request->tahun_ajar_id;
        $pengajar->save();

        Alert::success('Sukses!', 'Data berhasil diubah');
        return redirect(route('admin.pengajar.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pengajar = Pengajar::findOrFail($id);
        $pengajar->delete();

        Alert::success('Sukses!', 'Data berhasil dihapus');
        return redirect(route('admin.pengajar.index'));
    }
}

app/Http/Controllers/Api/PengajarController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Pengajar;

class PengajarController extends Controller
{
    public function getPengajar(Request $request) {
        $pengajar = Pengajar::with(['kelas', 'mapel'])->where('user_id', $request->id)->get();

        return response()->json([
            'status' => true,
            'data' => $pengajar
        ], 200);
    }
}

resources/views/pages/admin/pengajar/create.blade.php
@extends('layouts.app')

@section('title','Tambah Pengajar')

@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        <a href="{{ url()->previous() }}" class="btn btn-danger ml-auto mr-3">Kembali</a>
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="row d-flex justify-content-center">
                                        <div class="col-md-6">
                                            <form method="post" action="{{ route('admin.pengajar.store') }}">
                                                @csrf
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="user_id">Guru</label>
                                                            <select name="user_id" id="user_id" data-toggle="select" class="form-control @error('user_id') is-invalid @enderror">
                                                                <option value="">Pilih guru</option>
                                                                @foreach ($guru as $g)
                                                                    <option value="{{ $g->id }}" @if(old('user_id') == $g->id) selected @endif>{{ $g->name }}</option>
                                                                @endforeach
                                                            </select>
                                                            @error('user_id')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                            @enderror   
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="mapel_id">Mapel</label>
                                                            <select name="mapel_id" id="mapel_id" data-toggle="select" class="form-control @error('mapel_id') is-invalid @enderror">
                                                                <option value="">Pilih mapel</option>
                                                                @foreach ($mapel as $m)
                                                                    <option value="{{ $m->id }}" @if(old('mapel_id') == $m->id) selected @endif>{{ $m->nama_mapel . ' | ' . $m->tingkat}}</option>
                                                                @endforeach
                                                            </select>
                                                            @error('mapel_id')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                            @enderror   
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="kelas_id">Kelas</label>
                                                            <select name="kelas_id" id="kelas_id" data-toggle="select" class="form-control @error('kelas_id') is-invalid @enderror">
                                                                <option value="">Pilih kelas</option>
                                                                @foreach ($kelas as $k)
                                                                    <option value="{{ $k->id }}" @if(old('kelas_id') == $k->id) selected @endif>{{ $k->nama_kelas }}</option>
                                                                @endforeach
                                                            </select>
                                                            @error('kelas_id')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                            @enderror   
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="tahun_ajar_id">Tahun ajar</label>
                                                            <select name="tahun_ajar_id" id="tahun_ajar_id" data-toggle="select" class="form-control @error('tahun_ajar_id') is-invalid @enderror">
                                                                <option value="">Pilih tahun ajar</option>
                                                                @foreach ($tahunajar as $th)
                                                                    <option value="{{ $th->id }}" @if(old('tahun_ajar_id') == $th->id) selected @endif>{{ $th->periode . '-' . ($th->periode+1)}}</option>
                                                                @endforeach
                                                            </select>
                                                            @error('tahun_ajar_id')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                            @enderror   
                                                        </div>
                                                    </div>
                                                </div>
                                                <button type="submit" class="btn btn-primary float-right">Submit</button>                                            
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
@endsection

@section('script')
    
@endsection

resources/views/pages/admin/pengajar/edit.blade.php
@extends('layouts.app')

@section('title','Edit Pengajar')

@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        <a href="{{ url()->previous() }}" class="btn btn-danger ml-auto mr-3">Kembali</a>
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="row d-flex justify-content-center">
                                        <div class="col-md-6">
                                            <form method="post" action="{{ route('admin.pengajar.update', $pengajar->id) }}">
                                                @method('put')
                                                @csrf
                                                <div class="form-group">
                                                    <label for="user_id">Guru</label>
                                                    <input name="user_id" id="user_id" type="text" class="form-control" value="{{ $pengajar->user->name }}" readonly disabled>
                                                </div>
                                                <div class="form-group">
                                                    <label for="mapel_id">Mapel</label>
                                                    <select name="mapel_id" id="mapel_id" data-toggle="select" class="form-control @error('mapel_id') is-invalid @enderror">
                                                        <option value="">Pilih mapel</option>
                                                        @foreach ($mapel as $m)
                                                            <option value="{{ $m->id }}" @if($pengajar->mapel_id == $m->id) selected @endif>{{ $m->nama_mapel }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                                <div class="form-group">
                                                    <label for="kelas_id">Kelas</label>
                                                    <select name="kelas_id" id="kelas_id" data-toggle="select" class="form-control @error('kelas_id') is-invalid @enderror">
                                                        <option value="">Pilih Kelas</option>
                                                        @foreach ($kelas as $k)
                                                            <option value="{{ $k->id }}" @if($pengajar->kelas_id == $k->id) selected @endif>{{ $k->nama_kelas }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                                <div class="form-group">
                                                    <label for="tahun_ajar_id">Tahun ajar</label>
                                                    <select name="tahun_ajar_id" id="tahun_ajar_id" data-toggle="select" class="form-control @error('tahun_ajar_id') is-invalid @enderror">
                                                        <option value="">Pilih tahun ajar</option>
                                                        @foreach ($tahunajar as $th)
                                                            <option value="{{ $th->id }}" @if($pengajar->tahun_ajar_id == $th->id) selected @endif>{{ $th->periode . '-' . ($th->periode+1)}}</option>
                                                        @endforeach
                                                    </select>  
                                                </div>
                                                <button type="submit" class="btn btn-primary float-right">Submit</button>                                            
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
@endsection

@section('script')
    
@endsection

resources/views/pages/admin/pengajar/index.blade.php
@extends('layouts.app')

@section('title','Pengajar')
    
@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        @can('add-pengajar')
                                        <a href="{{ route('admin.pengajar.create') }}" class="btn btn-primary ml-auto mr-3"><i class="fas fa-plus-square"></i></a>
                                        @endcan
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="row">
                                        <div class="col-md-6 ml-auto mr-2">
                                            <form action="{{ url()->current() }}">
                                                <div class="search-form search-form--light m-2">
                                                    <input name="search" type="text" class="form-control search" placeholder="Search">
                                                    <button class="btn" type="submit" role="button"><i class="material-icons">search</i></button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="table-responsive">
                                        <table id="table" class="table table-striped thead-border-top-0">
                                            <thead>
                                                <tr>
                                                    <th>No.</th>
                                                    <th>Guru</th>
                                                    <th>Kelas</th>
                                                    <th>Mapel</th>
                                                    <th style="width: 200px">Action</th>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: {
                url: "{{ route('admin.pengajar.index') }}"
            },
            responsive: true,
            "columns": [
                {
                    data: 'id',
                    name: 'id'
                },
                {
                    data: 'user.name',
                    name: 'user.name'
                },
                {
                    data: 'kelas.nama_kelas',
                    name: 'kelas.nama_kelas'
                },
                {
                    data: 'mapel.nama_mapel',
                    name: 'mapel.nama_mapel'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ]
        })

        $('#table').on('click', '.btn-danger[data-remote]', function (e) { 
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            var url = $(this).data('remote');
            // confirm then
            Swal.fire({
                title: 'Apakah anda yakin?',
                text: "Data yang dihapus tidak bisa dikembalikan lagi!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya!',
                cancelButtonText: 'Tidak'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: url,
                        type: 'DELETE',
                        dataType: 'json',
                        data: {method: '_DELETE', submit: true}
                    }).always(function (data) {
                        Swal.fire(
                        'Terhapus!',
                        'Data berhasil dihapus.',
                        'success'
                        )
                        $('#table').DataTable().draw(false);
                    });
                }
            })
        });
    })
</script>
@endsection