routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/author', function() {
    return view('author.index');
})->name('author');

Auth::routes(['register' => false, 'reset' => false, 'confirm' => false]);

Route::group(['namespace' => 'Admin',  'prefix' => 'admin', 'middleware' => ['auth', 'role:super-admin|admin']], function () {
    Route::name('admin.')->group(function () {
        // MASTER
        Route::resource('/kelas', 'KelasController', ['except' => ['show']])->middleware('permission:see-kelas|add-kelas|edit-kelas|delete-kelas');
        Route::resource('/siswa', 'SiswaController', ['except' => ['show']])->middleware('permission:see-siswa|add-siswa|edit-siswa|delete-siswa');
        
        // Guru
        Route::resource('/guru', 'UserController', ['except' => ['show']])->middleware('permission:see-guru|add-guru|edit-guru|delete-guru');
        Route::resource('/mapel', 'MapelController', ['except' => ['show']])->middleware('permission:see-mapel|add-mapel|edit-mapel|delete-mapel');
        Route::resource('/pengajar', 'PengajarController', ['except' => ['show']])->middleware('permission:see-pengajar|add-pengajar|edit-pengajar|delete-pengajar');
        Route::resource('/jurusan', 'JurusanController', ['except' => ['show']])->middleware('permission:see-jurusan|add-jurusan|edit-jurusan|delete-jurusan');
        Route::resource('/wali-kelas', 'WaliKelasController', ['except' => ['show', 'edit', 'update']]);
        Route::resource('/tahun-ajar', 'TahunAjarController', ['except' => ['show']])->middleware('permission:see-tahun-ajar|add-tahun-ajar|edit-tahun-ajar|delete-tahun-ajar');
        // Settings Route
        Route::group(['middleware' => ['role:super-admin|admin', 'permission:edit-settings']], function () {
            Route::get('/settings', 'SettingController@index')->name('settings.index');
            Route::put('/settings', 'SettingController@update')->name('settings.update');
        });
    });
});

Route::group(['middleware' => ['auth', 'role:super-admin|admin|user']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    // Jurnal
    Route::resource('/jurnal', 'JurnalController');
    Route::resource('/wali-kelas', 'WaliKelasController');
    Route::get('/all-jurnal', 'JurnalController@all')->name('jurnal.all');
    Route::get('/jurnal/detail/{id}', 'JurnalController@show_detail')->name('jurnal.detail');
    Route::post('/jurnal/siswa', 'JurnalController@siswa')->name('jurnal.siswa');
    Route::post('/jurnal/mapel', 'JurnalController@mapel')->name('jurnal.mapel');
    Route::get('/laporan/print-sdm', 'LaporanController@print')->name('coba-print');
    // Route::get('/laporan/all-coba-print', 'LaporanController@allprintsdm')->name('all-coba-print');
    Route::get('/laporan/sdm', 'LaporanController@indexsdm')->name('laporan_sdm.index')->middleware('permission:see-laporan-sdm');
    // Route::get('/laporan/all-sdm', 'LaporanController@indexallsdm')->name('laporan_sdm.all')->middleware('permission:see-laporan-sdm');
    Route::get('/laporan/bk', 'LaporanController@indexbk')->name('laporan_bk.index')->middleware('permission:see-laporan-bk');
    
    // Edit Profile
    Route::get('/profile', 'UserController@index')->name('user.index');
    Route::put('/profile', 'UserController@updateProfile')->name('user.updateProfile');

    // Edit Password
    Route::get('/edit-password', 'UserController@password')->name('user.password');
    Route::put('/edit-password', 'UserController@updatePassword')->name('user.updatePassword');
});

app/Models/Mapel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use App\Models\Jurusan;
use App\Models\Jurnal;
use App\Models\Pengajar;

class Mapel extends Model
{
    public $timestamps = false;
    protected $table = 'mapel';

    public function jurusan() {
        return $this->belongsTo(Jurusan::class);
    }

    public static function getPossibleEnumValues($name) {
        $instance = new static; // create an instance of the model to be able to get the table name
        $type = DB::select( DB::raw('SHOW COLUMNS FROM '.$instance->getTable().' WHERE Field = "'.$name.'"') )[0]->Type;
        preg_match('/^enum\((.*)\)$/', $type, $matches);
        $enum = array();
        foreach(explode(',', $matches[1]) as $value){
            $v = trim( $value, "'" );
            $enum[] = $v;
        }
        return $enum;
    }

    public function jurnal() {
        return $this->hasMany(Jurnal::class);
    }

    public function pengajar() {
        return $this->hasMany(Pengajar::class);
    }
}

app/Http/Controllers/Admin/MapelController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Mapel\MapelCreateUpdateRequest;
use App\Models\Mapel;
use App\Models\Jurusan;
use DataTables;
use Alert;

class MapelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $mapel = Mapel::with('jurusan')->get();
            return DataTables::of($mapel)
                            ->addColumn('action', function($mapel) {
                                $button = "<a href=".route('admin.mapel.edit', $mapel->id)." class='btn btn-success'><i class='far fa-edit'></i></a>";
                                $button .= "&nbsp;&nbsp;";
                                $button .= "<button class='btn btn-danger' data-remote='".route('admin.mapel.destroy', $mapel->id)."'><i class='fas fa-trash-alt'></i></button>";
                                return $button;
                            })
                            ->rawColumns(['action'])
                            ->make(true);
        }


        return view('pages.admin.mapel.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kelompok = Mapel::getPossibleEnumValues('kelompok');
        $tingkat = Mapel::getPossibleEnumValues('tingkat');
        $jurusan = Jurusan::get();

        return view('pages.admin.mapel.create', compact('kelompok','tingkat','jurusan'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(MapelCreateUpdateRequest $request)
    {
        $mapel = new Mapel;
        $mapel->nama_mapel = $request->nama_mapel;
        $mapel->kelompok = $request->kelompok;
        $mapel->tingkat = $request->tingkat;
        $mapel->keterangan = $request->keterangan;
        $mapel->jumlah_jam = $request->jumlah_jam;
        $mapel->jurusan_id = $request->jurusan_id;
        $mapel->save();

        Alert::success('Sukses!', 'Data berhasil ditambahkan');
        return redirect(route('admin.mapel.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mapel = Mapel::findOrFail($id);
        $kelompok = Mapel::getPossibleEnumValues('kelompok');
        $tingkat = Mapel::getPossibleEnumValues('tingkat');
        $jurusan = Jurusan::get();

        return view('pages.admin.mapel.edit', compact('mapel','kelompok','tingkat','jurusan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(MapelCreateUpdateRequest $request, $id)
    {
        $mapel = Mapel::findOrFail($id);
        $mapel->nama_mapel = $request->nama_mapel;
        $mapel->kelompok = $request->kelompok;
        $mapel->tingkat = $request->tingkat;
        $mapel->jumlah_jam = $request->jumlah_jam;
        $mapel->jurusan_id = $request->jurusan_id;
        $mapel->save();

        Alert::success('Sukses!', 'Data berhasil diubah');
        return redirect(route('admin.mapel.index'));
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $mapel = Mapel::findOrFail($id);
        $mapel->delete();

        Alert::success('Sukses!', 'Data berhasil dihapus');
        return redirect(route('admin.mapel.index'));
    }
}

app/Http/Controllers/Api/MapelController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Mapel;

class MapelController extends Controller
{
    public function getMapel(Request $request) {
        $mapel = Mapel::where('id', $request->id)->first();

        return response()->json([
            'status' => true,
            'data' => $mapel
        ], 200);
    }
}

resources/views/pages/admin/mapel/create.blade.php
@extends('layouts.app')

@section('title','Tambah Mapel')

@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        <a href="{{ url()->previous() }}" class="btn btn-danger ml-auto mr-3">Kembali</a>
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="row d-flex justify-content-center">
                                        <div class="col-md-6">
                                            <form method="post" action="{{ route('admin.mapel.store') }}">
                                                @csrf
                                                <div class="form-group">
                                                    <label for="nama_mapel">Mata Pelajaran</label>
                                                    <input name="nama_mapel" id="nama_mapel" type="text" class="form-control @error('nama_mapel') is-invalid @enderror" value="{{ old('nama_mapel') }}" placeholder="Mata Pelajaran">
                                                    @error('nama_mapel')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="kelompok">Kelompok</label>
                                                    <select name="kelompok" id="kelompok" data-toggle="select" class="form-control @error('kelompok') is-invalid @enderror" style="text-transform: capitalize;">
                                                        <option value="">Pilih kelompok </option>
                                                        @foreach ($kelompok as $k)
                                                            <option value="{{ $k }}" @if(old('kelompok') == $k) selected @endif>{{ $k }}</option>
                                                        @endforeach
                                                    </select>
                                                    @error('kelompok')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="tingkat">Tingkat</label>
                                                    <select name="tingkat" id="tingkat" data-toggle="select" class="form-control @error('tingkat') is-invalid @enderror" style="text-transform: capitalize;">
                                                        <option value="">Pilih tingkat </option>
                                                        @foreach ($tingkat as $t)
                                                            <option value="{{ $t }}" @if(old('tingkat') == $t) selected @endif>{{ $t }}</option>
                                                        @endforeach
                                                    </select>
                                                    @error('tingkat')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="keterangan">Keterangan</label>
                                                    <textarea name="keterangan" id="keterangan" class="form-control"></textarea>
                                                    @error('tingkat')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="jumlah_jam">Jumlah Jam</label>
                                                    <input name="jumlah_jam" id="jumlah_jam" type="text" class="form-control @error('jumlah_jam') is-invalid @enderror" value="{{ old('jumlah_jam') }}" placeholder="Jumlah Jam">
                                                    @error('jumlah_jam')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="jurusan_id">Jurusan</label>
                                                    <select name="jurusan_id" id="jurusan_id" data-toggle="select" class="form-control @error('jurusan_id') is-invalid @enderror">
                                                        <option value="">Pilih Jurusan</option>
                                                        @foreach ($jurusan as $j)
                                                            <option value="{{ $j->id }}" @if (old('jurusan_id') == $j->id) selected @endif>{{ $j->nama_jurusan }}</option>
                                                        @endforeach
                                                    </select>
                                                    @error('jurusan_id')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <button type="submit" class="btn btn-primary float-right">Submit</button>                                            
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
@endsection

@section('script')
    
@endsection

resources/views/pages/admin/mapel/edit.blade.php
@extends('layouts.app')

@section('title','Edit Mapel')

@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        <a href="{{ url()->previous() }}" class="btn btn-danger ml-auto mr-3">Kembali</a>
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="row d-flex justify-content-center">
                                        <div class="col-md-6">
                                            <form method="post" action="{{ route('admin.mapel.update', $mapel->id) }}">
                                                @method('put')
                                                @csrf
                                                <div class="form-group">
                                                    <label for="nama_mapel">Mata Pelajaran</label>
                                                    <input name="nama_mapel" id="nama_mapel" type="text" class="form-control @error('nama_mapel') is-invalid @enderror" value="{{ $mapel->nama_mapel }}" placeholder="Mata Pelajaran">
                                                    @error('nama_mapel')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="kelompok">Kelompok</label>
                                                    <select name="kelompok" id="kelompok" data-toggle="select" class="form-control @error('kelompok') is-invalid @enderror" style="text-transform: capitalize;">
                                                        <option value="">Pilih kelompok </option>
                                                        @foreach ($kelompok as $k)
                                                            <option value="{{ $k }}" @if($mapel->kelompok == $k) selected @endif>{{ $k }}</option>
                                                        @endforeach
                                                    </select>
                                                    @error('kelompok')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="tingkat">Tingkat</label>
                                                    <select name="tingkat" id="tingkat" data-toggle="select" class="form-control @error('tingkat') is-invalid @enderror" style="text-transform: capitalize;">
                                                        <option value="">Pilih tingkat </option>
                                                        @foreach ($tingkat as $t)
                                                            <option value="{{ $t }}" @if($mapel->tingkat == $t) selected @endif>{{ $t }}</option>
                                                        @endforeach
                                                    </select>
                                                    @error('tingkat')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="jumlah_jam">Jumlah Jam</label>
                                                    <input name="jumlah_jam" id="jumlah_jam" type="text" class="form-control @error('jumlah_jam') is-invalid @enderror" value="{{ $mapel->jumlah_jam }}" placeholder="Jumlah Jam">
                                                    @error('jumlah_jam')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="jurusan_id">Jurusan</label>
                                                    <select name="jurusan_id" id="jurusan_id" data-toggle="select" class="form-control @error('jurusan_id') is-invalid @enderror">
                                                        <option value="">Pilih Jurusan</option>
                                                        @foreach ($jurusan as $j)
                                                            <option value="{{ $j->id }}" @if($mapel->jurusan_id == $j->id) selected @endif>{{ $j->nama_jurusan }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                                <button type="submit" class="btn btn-primary float-right">Submit</button>                                            
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
@endsection

@section('script')
    
@endsection

resources/views/pages/admin/mapel/index.blade.php
@extends('layouts.app')

@section('title','Mapel')
    
@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        @can('add-mapel')
                                        <a href="{{ route('admin.mapel.create') }}" class="btn btn-primary ml-auto mr-3"><i class="fas fa-plus-square"></i></a>
                                        @endcan
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="table-responsive">
                                        <table id="table" class="table table-striped thead-border-top-0">
                                            <thead>
                                                <tr>
                                                    <th>No.</th>
                                                    <th>Nama</th>
                                                    <th>Kelompok</th>
                                                    <th>Tingkat</th>
                                                    <th>Jumlah Jam</th>
                                                    <th width="20%">Jurusan</th>
                                                    <th style="width: 200px">Action</th>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: {
                url: "{{ route('admin.mapel.index') }}"
            },
            responsive: true,
            "columns": [
                {
                    data: 'id',
                    name: 'id'
                },
                {
                    data: 'nama_mapel',
                    name: 'nama_mapel'
                },
                {
                    data: 'kelompok',
                    name: 'kelompok'
                },
                {
                    data: 'tingkat',
                    name: 'tingkat'
                },
                {
                    data: 'jumlah_jam',
                    name: 'jumlah_jam'
                },
                {
                    data: 'jurusan.nama_jurusan',
                    name: 'jurusan.nama_jurusan'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ]
        })

        $('#table').on('click', '.btn-danger[data-remote]', function (e) { 
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            var url = $(this).data('remote');
            // confirm then
            Swal.fire({
                title: 'Apakah anda yakin?',
                text: "Data yang dihapus tidak bisa dikembalikan lagi!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya!',
                cancelButtonText: 'Tidak'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: url,
                        type: 'DELETE',
                        dataType: 'json',
                        data: {method: '_DELETE', submit: true}
                    }).always(function (data) {
                        Swal.fire(
                        'Terhapus!',
                        'Data berhasil dihapus.',
                        'success'
                        )
                        $('#table').DataTable().draw(false);
                    });
                }
            })
        });
    })
</script>
@endsection