routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/author', function() {
    return view('author.index');
})->name('author');

Auth::routes(['register' => false, 'reset' => false, 'confirm' => false]);

Route::group(['namespace' => 'Admin',  'prefix' => 'admin', 'middleware' => ['auth', 'role:super-admin|admin']], function () {
    Route::name('admin.')->group(function () {
        // MASTER
        Route::resource('/kelas', 'KelasController', ['except' => ['show']])->middleware('permission:see-kelas|add-kelas|edit-kelas|delete-kelas');
        Route::resource('/siswa', 'SiswaController', ['except' => ['show']])->middleware('permission:see-siswa|add-siswa|edit-siswa|delete-siswa');
        
        // Guru
        Route::resource('/guru', 'UserController', ['except' => ['show']])->middleware('permission:see-guru|add-guru|edit-guru|delete-guru');
        Route::resource('/mapel', 'MapelController', ['except' => ['show']])->middleware('permission:see-mapel|add-mapel|edit-mapel|delete-mapel');
        Route::resource('/pengajar', 'PengajarController', ['except' => ['show']])->middleware('permission:see-pengajar|add-pengajar|edit-pengajar|delete-pengajar');
        Route::resource('/jurusan', 'JurusanController', ['except' => ['show']])->middleware('permission:see-jurusan|add-jurusan|edit-jurusan|delete-jurusan');
        Route::resource('/wali-kelas', 'WaliKelasController', ['except' => ['show', 'edit', 'update']]);
        Route::resource('/tahun-ajar', 'TahunAjarController', ['except' => ['show']])->middleware('permission:see-tahun-ajar|add-tahun-ajar|edit-tahun-ajar|delete-tahun-ajar');
        // Settings Route
        Route::group(['middleware' => ['role:super-admin|admin', 'permission:edit-settings']], function () {
            Route::get('/settings', 'SettingController@index')->name('settings.index');
            Route::put('/settings', 'SettingController@update')->name('settings.update');
        });
    });
});

Route::group(['middleware' => ['auth', 'role:super-admin|admin|user']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    // Jurnal
    Route::resource('/jurnal', 'JurnalController');
    Route::resource('/wali-kelas', 'WaliKelasController');
    Route::get('/all-jurnal', 'JurnalController@all')->name('jurnal.all');
    Route::get('/jurnal/detail/{id}', 'JurnalController@show_detail')->name('jurnal.detail');
    Route::post('/jurnal/siswa', 'JurnalController@siswa')->name('jurnal.siswa');
    Route::post('/jurnal/mapel', 'JurnalController@mapel')->name('jurnal.mapel');
    Route::get('/laporan/print-sdm', 'LaporanController@print')->name('coba-print');
    // Route::get('/laporan/all-coba-print', 'LaporanController@allprintsdm')->name('all-coba-print');
    Route::get('/laporan/sdm', 'LaporanController@indexsdm')->name('laporan_sdm.index')->middleware('permission:see-laporan-sdm');
    // Route::get('/laporan/all-sdm', 'LaporanController@indexallsdm')->name('laporan_sdm.all')->middleware('permission:see-laporan-sdm');
    Route::get('/laporan/bk', 'LaporanController@indexbk')->name('laporan_bk.index')->middleware('permission:see-laporan-bk');
    
    // Edit Profile
    Route::get('/profile', 'UserController@index')->name('user.index');
    Route::put('/profile', 'UserController@updateProfile')->name('user.updateProfile');

    // Edit Password
    Route::get('/edit-password', 'UserController@password')->name('user.password');
    Route::put('/edit-password', 'UserController@updatePassword')->name('user.updatePassword');
});

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use App\Models\Absen;
use App\Models\Kelas;

class Siswa extends Model
{
    public $timestamps = false;
    protected $table = 'siswa';
    protected $guarded = [];

    public function absen() {
        return $this->hasMany(Absen::class, 'nisn', 'nisn');
    }

    public function kelas() {
        return $this->belongsTo(Kelas::class);
    }
}

app/Http/Controllers/Admin/SiswaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Kelas;
use App\Models\Siswa;
use App\Http\Requests\Siswa\SiswaCreateRequest, App\Http\Requests\Siswa\SiswaUpdateRequest;
use DataTables;
use Alert;

class SiswaController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $siswa = Siswa::with('kelas')->get();
            return DataTables::of($siswa)
                            ->addColumn('status', function($siswa){
                                $btnStatus = $siswa->status == 'aktif' ? 'success': 'danger';
                                return "<button class='btn text-capitalize btn-$btnStatus' disabled>$siswa->status</button>";
                            }) 
                            ->addColumn('action', function($siswa) {
                                $button = "<a href=".route('admin.siswa.edit', $siswa->id)." class='btn btn-success'><i class='far fa-edit'></i></a>";
                                $button .= "&nbsp;&nbsp;";
                                $button .= "<button class='btn btn-danger' data-remote='".route('admin.siswa.destroy', $siswa->id)."'><i class='fas fa-trash-alt'></i></button>";
                                return $button;
                            })
                            ->rawColumns(['status','action'])
                            ->make(true);
        }

        return view('pages.admin.siswa.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kelas = Kelas::get();

        return view('pages.admin.siswa.create', compact('kelas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SiswaCreateRequest $request)
    {
        $siswa = new Siswa;
        $siswa->nis = $request->nis;
        $siswa->nisn = $request->nisn;
        $siswa->nama_siswa = $request->nama_siswa;
        $siswa->kelas_id = $request->kelas_id;
        $siswa->keterangan = $request->keterangan;
        $siswa->status = $request->status == 1 ? 'aktif' : 'nonaktif';
        $siswa->save();

        Alert::success('Sukses!', 'Data berhasil ditambahkan');
        return redirect(route('admin.siswa.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $siswa = Siswa::findOrFail($id);
        $kelas = Kelas::get();

        return view('pages.admin.siswa.edit', compact('siswa', 'kelas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SiswaUpdateRequest $request, $id)
    {
        $siswa = Siswa::findOrFail($id);
        if(auth()->user()->hasRole('super-admin')) {
            $siswa->nis = $request->nis;
            $siswa->nisn = $request->nisn;
        }
        $siswa->nama_siswa = $request->nama_siswa;
        $siswa->kelas_id = $request->kelas_id;
        $siswa->keterangan = $request->keterangan;
        $siswa->status = $request->status == 1 ? 'aktif' : 'nonaktif';
        $siswa->save();

        Alert::success('Sukses!', 'Data berhasil diubah');
        return redirect(route('admin.siswa.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $siswa = Siswa::findOrFail($id);
        $siswa->delete();

        Alert::success('Sukses!', 'Data berhasil dihapus');
        return redirect(route('admin.siswa.index'));
    }
}

app/Http/Controllers/Api/SiswaController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Siswa;

class SiswaController extends Controller {

    public function login(Request $request)
    {
        $nis = $request->nis;
        $password = $request->password;

        $student = Siswa::where('nis', $nis)->first();

        if(!is_null($student) && $password == $nis . '*') {
            $student->toArray();

            return response()->json([
                "status" => true,
                "data" => [
                    "id" => $student["id"],
                    "name" => $student["nama_siswa"],
                    "kelas" => [
                        "kelas_id" => $student["kelas"]["id"],
                        "kelas" => $student["kelas"]["nama_kelas"]
                    ],
                    "role" => "siswa"
                ],
            ], 200);
        } else {
            return response()->json([
                "status" => false,
                "data" => [
                    "message" => "Invalid Credentials"
                ]
            ], 401);
        }
    }
}

resources/views/pages/admin/siswa/create.blade.php
@extends('layouts.app')

@section('title','Tambah Siswa')

@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        <a href="{{ url()->previous() }}" class="btn btn-danger ml-auto mr-3">Kembali</a>
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="row d-flex justify-content-center">
                                        <div class="col-md-6">
                                            <form method="post" action="{{ route('admin.siswa.store') }}">
                                                @csrf
                                                <div class="form-group">
                                                    <label for="nis">NIS</label>
                                                    <input name="nis" id="nis" type="text" class="form-control @error('nis') is-invalid @enderror" value="{{ old('nis') }}" placeholder="NIS">
                                                    @error('nis')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="nisn">NISN</label>
                                                    <input name="nisn" id="nisn" type="text" class="form-control @error('nisn') is-invalid @enderror" value="{{ old('nisn') }}" placeholder="NISN">
                                                    @error('nisn')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="siswa">Siswa</label>
                                                    <input name="nama_siswa" id="nama_siswa" type="text" class="form-control @error('nama_siswa') is-invalid @enderror" value="{{ old('nama_siswa') }}" placeholder="Siswa">
                                                    @error('nama_siswa')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="kelas">Kelas</label>
                                                    <select name="kelas_id" id="kelas_id" data-toggle="select" class="form-control @error('kelas_id') is-invalid @enderror">
                                                        <option value="">Pilih Kelas</option>
                                                        @foreach ($kelas as $k)
                                                            <option value="{{ $k->id }}" @if(old('kelas_id') == $k->id) selected @endif>{{ $k->nama_kelas }}</option>
                                                        @endforeach
                                                    </select>
                                                    @error('kelas_id')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="keterangan">Keterangan</label>
                                                    <textarea name="keterangan" id="keterangan" class="form-control" placeholder="Keterangan">{{ old('keterangan') }}</textarea>
                                                </div>
                                                <div class="form-group">
                                                    <label for="status">Status</label>
                                                    <br>
                                                    <div class="custom-control custom-checkbox-toggle custom-control-inline mr-1">
                                                        <input type="checkbox" name="status" id="status" value="1" class="custom-control-input">
                                                        <label class="custom-control-label" for="status">Status</label>
                                                    </div>
                                                    <label for="status" class="mb-0">Aktif</label>
                                                </div>
                                                <button type="submit" class="btn btn-primary float-right">Submit</button>                                            
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
@endsection

@section('script')
    
@endsection

resources/views/pages/admin/siswa/edit.blade.php
@extends('layouts.app')

@section('title','Edit Siswa')

@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        <a href="{{ url()->previous() }}" class="btn btn-danger ml-auto mr-3">Kembali</a>
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="row d-flex justify-content-center">
                                        <div class="col-md-6">
                                            <form method="post" action="{{ route('admin.siswa.update', $siswa->id) }}">
                                                @method('put')
                                                @csrf
                                                <div class="form-group">
                                                    <label for="nis">NIS</label>
                                                    <input  @if(auth()->user()->hasRole('super-admin')) name="nis" @endif id="nis" type="text" class="form-control @error('nis') is-invalid @enderror" value="{{ $siswa->nis }}" @if(!auth()->user()->hasRole('super-admin')) readonly disabled @endif>  
                                                    @error('nis')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror </div>
                                                <div class="form-group">
                                                    <label for="nisn">NISN</label>
                                                    <input @if(auth()->user()->hasRole('super-admin')) name="nisn" @endif id="nisn" type="text" class="form-control @error('nisn') is-invalid @enderror" value="{{ $siswa->nisn }}" @if(!auth()->user()->hasRole('super-admin')) readonly disabled @endif> 
                                                    @error('nisn')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror  
                                                </div>
                                                <div class="form-group">
                                                    <label for="siswa">Siswa</label>
                                                    <input name="nama_siswa" id="nama_siswa" type="text" class="form-control @error('nama_siswa') is-invalid @enderror" value="{{ $siswa->nama_siswa }}" placeholder="siswa">
                                                    @error('nama_siswa')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="kelas">Kelas</label>
                                                    <select name="kelas_id" id="kelas_id" data-toggle="select" class="form-control @error('kelas_id') is-invalid @enderror">
                                                        <option value="">Pilih Kelas</option>
                                                        @foreach ($kelas as $k)
                                                            <option value="{{ $k->id }}" @if($siswa->kelas_id == $k->id) selected @endif>{{ $k->nama_kelas }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                                <div class="form-group">
                                                    <label for="keterangan">Keterangan</label>
                                                    <textarea name="keterangan" id="keterangan" class="form-control" placeholder="Keterangan">{{ $siswa->keterangan }}</textarea>
                                                </div>
                                                <div class="form-group">
                                                    <label for="status">Status</label>
                                                    <br>
                                                    <div class="custom-control custom-checkbox-toggle custom-control-inline mr-1">
                                                        <input type="checkbox" name="status" id="status" value="1" class="custom-control-input" @if($siswa->status == 'aktif') checked @endif>
                                                        <label class="custom-control-label" for="status">Status</label>
                                                    </div>
                                                    <label for="status" class="mb-0">Aktif</label>
                                                </div>
                                                <button type="submit" class="btn btn-primary float-right">Submit</button>                                            
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
@endsection

@section('script')
    
@endsection

resources/views/pages/admin/siswa/index.blade.php
@extends('layouts.app')

@section('title','Siswa')
    
@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        @can('add-siswa')
                                        <a href="{{ route('admin.siswa.create') }}" class="btn btn-primary ml-auto mr-3"><i class="fas fa-plus-square"></i></a>
                                        @endcan
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="table-responsive">
                                        <table id="table" class="table table-striped thead-border-top-0">
                                            <thead>
                                                <tr>
                                                    <th>NIS</th>
                                                    <th>NISN</th>
                                                    <th>Nama</th>
                                                    <th>Kelas</th>
                                                    <th>Status</th>
                                                    <th style="width: 200px">Action</th>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: {
                url: "{{ route('admin.siswa.index') }}"
            },
            responsive: true,
            "columns": [
                {
                    data: 'nis',
                    name: 'nis'
                },
                {
                    data: 'nisn',
                    name: 'nisn'
                },
                {
                    data: 'nama_siswa',
                    name: 'nama_siswa'
                },
                {
                    data: 'kelas.nama_kelas',
                    name: 'kelas.nama_kelas'
                },
                {
                    data: 'status',
                    name: 'status'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ]
        })

        $('#table').on('click', '.btn-danger[data-remote]', function (e) { 
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            var url = $(this).data('remote');
            // confirm then
            Swal.fire({
                title: 'Apakah anda yakin?',
                text: "Data yang dihapus tidak bisa dikembalikan lagi!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya!',
                cancelButtonText: 'Tidak'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: url,
                        type: 'DELETE',
                        dataType: 'json',
                        data: {method: '_DELETE', submit: true}
                    }).always(function (data) {
                        Swal.fire(
                        'Terhapus!',
                        'Data berhasil dihapus.',
                        'success'
                        )
                        $('#table').DataTable().draw(false);
                    });
                }
            })
        });
    })
</script>
@endsection