routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/author', function() {
    return view('author.index');
})->name('author');

Auth::routes(['register' => false, 'reset' => false, 'confirm' => false]);

Route::group(['namespace' => 'Admin',  'prefix' => 'admin', 'middleware' => ['auth', 'role:super-admin|admin']], function () {
    Route::name('admin.')->group(function () {
        // MASTER
        Route::resource('/kelas', 'KelasController', ['except' => ['show']])->middleware('permission:see-kelas|add-kelas|edit-kelas|delete-kelas');
        Route::resource('/siswa', 'SiswaController', ['except' => ['show']])->middleware('permission:see-siswa|add-siswa|edit-siswa|delete-siswa');
        
        // Guru
        Route::resource('/guru', 'UserController', ['except' => ['show']])->middleware('permission:see-guru|add-guru|edit-guru|delete-guru');
        Route::resource('/mapel', 'MapelController', ['except' => ['show']])->middleware('permission:see-mapel|add-mapel|edit-mapel|delete-mapel');
        Route::resource('/pengajar', 'PengajarController', ['except' => ['show']])->middleware('permission:see-pengajar|add-pengajar|edit-pengajar|delete-pengajar');
        Route::resource('/jurusan', 'JurusanController', ['except' => ['show']])->middleware('permission:see-jurusan|add-jurusan|edit-jurusan|delete-jurusan');
        Route::resource('/wali-kelas', 'WaliKelasController', ['except' => ['show', 'edit', 'update']]);
        Route::resource('/tahun-ajar', 'TahunAjarController', ['except' => ['show']])->middleware('permission:see-tahun-ajar|add-tahun-ajar|edit-tahun-ajar|delete-tahun-ajar');
        // Settings Route
        Route::group(['middleware' => ['role:super-admin|admin', 'permission:edit-settings']], function () {
            Route::get('/settings', 'SettingController@index')->name('settings.index');
            Route::put('/settings', 'SettingController@update')->name('settings.update');
        });
    });
});

Route::group(['middleware' => ['auth', 'role:super-admin|admin|user']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    // Jurnal
    Route::resource('/jurnal', 'JurnalController');
    Route::resource('/wali-kelas', 'WaliKelasController');
    Route::get('/all-jurnal', 'JurnalController@all')->name('jurnal.all');
    Route::get('/jurnal/detail/{id}', 'JurnalController@show_detail')->name('jurnal.detail');
    Route::post('/jurnal/siswa', 'JurnalController@siswa')->name('jurnal.siswa');
    Route::post('/jurnal/mapel', 'JurnalController@mapel')->name('jurnal.mapel');
    Route::get('/laporan/print-sdm', 'LaporanController@print')->name('coba-print');
    // Route::get('/laporan/all-coba-print', 'LaporanController@allprintsdm')->name('all-coba-print');
    Route::get('/laporan/sdm', 'LaporanController@indexsdm')->name('laporan_sdm.index')->middleware('permission:see-laporan-sdm');
    // Route::get('/laporan/all-sdm', 'LaporanController@indexallsdm')->name('laporan_sdm.all')->middleware('permission:see-laporan-sdm');
    Route::get('/laporan/bk', 'LaporanController@indexbk')->name('laporan_bk.index')->middleware('permission:see-laporan-bk');
    
    // Edit Profile
    Route::get('/profile', 'UserController@index')->name('user.index');
    Route::put('/profile', 'UserController@updateProfile')->name('user.updateProfile');

    // Edit Password
    Route::get('/edit-password', 'UserController@password')->name('user.password');
    Route::put('/edit-password', 'UserController@updatePassword')->name('user.updatePassword');
});

app/Models/Jurusan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Mapel;

class Jurusan extends Model
{
    public $timestamps = false;
    protected $table = 'jurusan';

    public function mapel() {
        return $this->hasMany(Mapel::class);
    }
}

app/Http/Controllers/Admin/JurusanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Jurusan\JurusanCreateRequest, App\Http\Requests\Jurusan\JurusanUpdateRequest;
use App\Models\Jurusan;
use DataTables;
use Alert;

class JurusanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $jurusan = Jurusan::get();
            return DataTables::of($jurusan)
                            ->addColumn('action', function($jurusan) {
                                $button = "<a href=".route('admin.jurusan.edit', $jurusan->id)." class='btn btn-success'><i class='far fa-edit'></i></a>";
                                $button .= "&nbsp;&nbsp;";
                                $button .= "<button class='btn btn-danger' data-remote='".route('admin.jurusan.destroy', $jurusan->id)."'><i class='fas fa-trash-alt'></i></button>";
                                return $button;
                            })
                            ->rawColumns(['action'])
                            ->make(true);
        }

        return view('pages.admin.jurusan.index');
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        return view('pages.admin.jurusan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(JurusanCreateRequest $request)
    {
        $jurusan = new Jurusan;
        $jurusan->id = $request->id;
        $jurusan->nama_jurusan = $request->nama_jurusan;
        $jurusan->save();

        Alert::success('Sukses!', 'Data berhasil ditambahkan');
        return redirect(route('admin.jurusan.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $jurusan = Jurusan::findOrFail($id);

        return view('pages.admin.jurusan.edit', compact('jurusan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(JurusanUpdateRequest $request, $id)
    {
        $jurusan = Jurusan::findOrFail($id);
        $jurusan->nama_jurusan = $request->nama_jurusan;
        $jurusan->save();

        Alert::success('Sukses!', 'Data berhasil diubah');
        return redirect(route('admin.jurusan.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $jurusan = Jurusan::findOrFail($id);
        $jurusan->delete();

        Alert::success('Sukses!', 'Data berhasil dihapus');
        return redirect(route('admin.jurusan.index'));
    }
}

resources/views/pages/admin/jurusan/create.blade.php
@extends('layouts.app')

@section('title','Tambah Jurusan')

@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        <a href="{{ url()->previous() }}" class="btn btn-danger ml-auto mr-3">Kembali</a>
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="row d-flex justify-content-center">
                                        <div class="col-md-6">
                                            <form method="post" action="{{ route('admin.jurusan.store') }}">
                                                @csrf
                                                <div class="form-group">
                                                    <label for="id">ID Jurusan</label>
                                                    <input name="id" id="id" type="text" class="form-control @error('id') is-invalid @enderror" value="{{ old('id') }}" placeholder="ID Jurusan">
                                                    @error('id')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="jurusan">Jurusan</label>
                                                    <input name="nama_jurusan" id="nama_jurusan" type="text" class="form-control @error('nama_jurusan') is-invalid @enderror" value="{{ old('nama_jurusan') }}" placeholder="Jurusan">
                                                    @error('nama_jurusan')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <button type="submit" class="btn btn-primary float-right">Submit</button>                                            
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
@endsection

@section('script')
    
@endsection

resources/views/pages/admin/jurusan/edit.blade.php
@extends('layouts.app')

@section('title','Edit Jurusan')

@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        <a href="{{ url()->previous() }}" class="btn btn-danger ml-auto mr-3">Kembali</a>
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="row d-flex justify-content-center">
                                        <div class="col-md-6">
                                            <form method="post" action="{{ route('admin.jurusan.update', $jurusan->id) }}">
                                                @method('put')
                                                @csrf
                                                <div class="form-group">
                                                    <label for="id">ID Jurusan</label>
                                                    <input id="id" type="text" class="form-control @error('id') is-invalid @enderror" value="{{ $jurusan->id }}" placeholder="ID Jurusan" readonly disabled>
                                                    @error('id')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <div class="form-group">
                                                    <label for="jurusan">Jurusan</label>
                                                    <input name="nama_jurusan" id="nama_jurusan" type="text" class="form-control @error('nama_jurusan') is-invalid @enderror" value="{{ $jurusan->nama_jurusan }}" placeholder="Jurusan">
                                                    @error('nama_jurusan')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror   
                                                </div>
                                                <button type="submit" class="btn btn-primary float-right">Submit</button>                                            
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                </div>
                        </div>
                    </div>
                </div>
@endsection

@section('script')
    
@endsection

resources/views/pages/admin/jurusan/index.blade.php
@extends('layouts.app')

@section('title','Jurusan')
    
@section('content')
                <div class="container-fluid page__container mt-4">
                    <div class="row">
                        <div class="col-lg">
                            <div class="card">
                                <div class="card-header card-header-large bg-white">
                                    <div class="row d-flex">
                                        <div class="col-md-6">
                                            <h5 class="m-0">@yield('title')</h5>
                                        </div>
                                        @can('add-jurusan')
                                        <a href="{{ route('admin.jurusan.create') }}" class="btn btn-primary ml-auto mr-3"><i class="fas fa-plus-square"></i></a>
                                        @endcan
                                    </div>
                                </div>
                                <div class="card-body button-list">
                                    <div class="table-responsive">
                                        <table id="table" class="table table-striped thead-border-top-0">
                                            <thead>
                                                <tr>
                                                    <th>id</th>
                                                    <th>Jurusan</th>
                                                    <th style="width: 200px">Action</th>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: {
                url: "{{ route('admin.jurusan.index') }}"
            },
            responsive: true,
            "columns": [
                {
                    data: 'id',
                    name: 'id'
                },
                {
                    data: 'nama_jurusan',
                    name: 'nama_jurusan'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ]
        })

        $('#table').on('click', '.btn-danger[data-remote]', function (e) { 
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            var url = $(this).data('remote');
            // confirm then
            Swal.fire({
                title: 'Apakah anda yakin?',
                text: "Data yang dihapus tidak bisa dikembalikan lagi!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya!',
                cancelButtonText: 'Tidak'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: url,
                        type: 'DELETE',
                        dataType: 'json',
                        data: {method: '_DELETE', submit: true}
                    }).always(function (data) {
                        Swal.fire(
                        'Terhapus!',
                        'Data berhasil dihapus.',
                        'success'
                        )
                        $('#table').DataTable().draw(false);
                    });
                }
            })
        });
    })
</script>
@endsection